address: ':8080'
tasks:
  - name: 'Show software versions'
    url: 'versions'
    workDir: '/home/sherab'
    commands:
      - [ 'go', 'version' ]
      - [ 'python', '--version' ]
      - [ 'foobar', '--version' ]
