address: ':8080'
tasks:
  - name: 'Show software versions'
    url: 'versions'
    workDir: '/home/sherab'
    commands:
      - [ 'go', 'version' ]
      - [ 'python', '--version' ]
      - [ 'foobar', '--version' ]
  - name: 'Update the application'
    url: 'update-uplication'
    workDir: '/home/sherab/docker-applications'
    commands:
      - [ 'pwd' ]
      - [ 'docker-compose', 'down' ]
      - [ 'docker-compose', 'pull' ]
      - [ 'docker-compose', 'up' ]
