name: vicegerent
base: core20
version: git
summary: Run predefined sets of commands in the server invoked by an HTTP call.
description: |
  Vicegerent is a small Go application which helps you to run predefined sets of commands
  in the server invoked by an HTTP call.

  An example usecase would be updateing Docker containers from a CI/CD script
  without giving SSH access to the server.

grade: stable
confinement: classic

parts:
  vicegerent:
    plugin: go
    source: ./src
apps:
  daemon:
    command: 'bin/vicegerent'
    daemon: simple
